version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:20.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -DskipTests

orbs:
  maven: circleci/maven@1.4.1
  tcc: atomicjar/testcontainers-cloud-orb@0.1.0

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:20.0'

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
          context: Testcontainers
          pre-steps:
            - tcc/setup
      - analyze:
          context: SonarCloud